config-version: 1

# The root folder for the database change scripts
root-folder: './migration'

# The modules folder for jinja macros and templates to be used across multiple scripts.
modules-folder: null

# The name of the snowflake account (e.g. xy12345.east-us-2.azure)
snowflake-account: 'vakffqs-ni21132'

# The name of the snowflake user
snowflake-user: Audace

# The name of the default role to use. Can be overrideen in the change scripts.
snowflake-role: 'SYSADMIN'

# The name of the default warehouse to use. Can be overridden in the change scripts.
snowflake-warehouse: 'COMPUTE_WH'

# The name of the default database to use. Can be overridden in the change scripts.
snowflake-database: 'DEMO_DB'

# Used to override the default name of the change history table (the default is METADATA.SCHEMACHANGE.CHANGE_HISTORY)
change-history-table: 'DEMO_DB.SCHEMACHANGE.CHANGE_HISTORY'


# Create the change history schema and table, if they do not exist (the default is False)
create-change-history-table: true

# Enable autocommit feature for DML commands (the default is False)
autocommit: false

# Display verbose debugging details during execution (the default is False)
verbose: true

# Run schemachange in dry run mode (the default is False)
dry-run: false

# A string to include in the QUERY_TAG that is attached to every SQL statement executed
query-tag: 'SCHEMACHANGE_DEPLOY'